### ISSUE TITLE
rtp-over-tcp doesn't work with minisatip

### ISSUE THREAD

**Issue by stauraum** [rofafor/vdr-plugin-satip#47] opened 2018-01-16 10:13 UTC
I don't know whats wrong.

> root@bruno:~# vdr -V
> vdr (2.2.0/2.2.0) - The Video Disk Recorder
> conflictcheckonly (0.0.1) - Direct access to epgsearch's conflict check menu
> epgsearch (1.0.1.beta5) - search the EPG for repeats and more
> epgsearchonly (0.0.1) - Direct access to epgsearch's search menu
> live (0.3.0) - Live Interactive VDR Environment
> quickepgsearch (0.0.1) - Quick search for broadcasts
> restfulapi (0.2.6.5) - Offers a RESTful-API to retrieve data from VDR
> satip (2.2.5) - SAT>IP Devices
> streamdev-server (0.6.1-git) - VDR Streaming Server
> vdrmanager (0.14) - VDR-Manager plugin
> vnsiserver (1.5.2) - VDR-Network-Streaming-Interface (VNSI) Server

> ii  vdr-plugin-satip                       2.2.4+git20171118-f3fe1e amd64                    SAT>IP plugin for VDR

> ~ # ps -efl|grep minisat|grep -v grep
>   781 root       0:04 minisatip7 -f -g --satip-tcp
> ~ #
> 

> satip.CICAM = 0 0
> satip.DisabledFilters =
> satip.DisabledSources =
> satip.EnableCIExtension = 0
> satip.EnableEITScan = 0
> satip.OperatingMode = 3
> satip.TransportMode = 2

> 2018-01-09T11:28:52.563742+01:00 bruno vdr: [275] SATIP-ERROR: Connection timeout - retuning [device 0]
> 2018-01-09T11:28:52.566249+01:00 bruno vdr: [275] SATIP-ERROR: Detected invalid status code 454: rtsp://192.168.2.15/ [device 0]
> 2018-01-09T11:28:52.566573+01:00 bruno vdr: [275] SATIP-ERROR: Connect failed [device 0]
> 2018-01-09T11:28:57.838871+01:00 bruno vdr: [275] SATIP-ERROR: Connection timeout - retuning [device 0]
> 2018-01-09T11:28:57.841376+01:00 bruno vdr: [275] SATIP-ERROR: Detected invalid status code 454: rtsp://192.168.2.15/ [device 0]
> 2018-01-09T11:28:57.841698+01:00 bruno vdr: [275] SATIP-ERROR: Connect failed [device 0]
> 2018-01-09T11:29:03.112695+01:00 bruno vdr: [275] SATIP-ERROR: Connection timeout - retuning [device 0]
> 2018-01-09T11:29:03.115334+01:00 bruno vdr: [275] SATIP-ERROR: Detected invalid status code 454: rtsp://192.168.2.15/ [device 0]
> 2018-01-09T11:29:03.115645+01:00 bruno vdr: [275] SATIP-ERROR: Connect failed [device 0]
> 2018-01-09T11:29:08.387611+01:00 bruno vdr: [275] SATIP-ERROR: Connection timeout - retuning [device 0]
> 2018-01-09T11:29:08.390423+01:00 bruno vdr: [275] SATIP-ERROR: Detected invalid status code 454: rtsp://192.168.2.15/ [device 0]
> 2018-01-09T11:29:08.390741+01:00 bruno vdr: [275] SATIP-ERROR: Connect failed [device 0]

**Comment by rofafor** [comment] 2018-01-16 18:29
You should look at the minisatip logs, why it's replying 454.

**Comment by stauraum** [comment] 2018-01-18 12:40
i see nothing ... :-(

https://pastebin.com/Gas83jTk

**Comment by rofafor** [comment] 2018-01-19 07:22
There are plenty of "connection refused" messages in your log, so I'd check any firewall rules first. However, the error code 454 is "Session not found", but I don't know enough of minisatip internals what might be a cause for this:
```The RTSP session identifier value in the "Session:" header field of the request is missing, invalid, or has timed out. Returned when issuing the wrong session identifier value in a request.```

**Comment by 9000h** [comment] 2018-01-25 20:48
looks like you have a digibit r1 or similar, you should try to update the firmware 
https://github.com/perexg/satip-axe/issues/94#issuecomment-360391337

**Comment by stauraum** [comment] 2018-01-26 08:45
minisatip8 doesn't solve my issue :-(

`·
2018-01-26T09:42:59.491996+01:00 bruno vdr: [207] SATIP-ERROR: Connection timeout - retuning [device 0]                                     │····································
2018-01-26T09:42:59.494082+01:00 bruno vdr: [207] SATIP-ERROR: Detected invalid status code 454: rtsp://192.168.2.15/ [device 0]            │····································
2018-01-26T09:42:59.494405+01:00 bruno vdr: [207] SATIP-ERROR: Connect failed [device 0]   `

**Comment by 9000h** [comment] 2018-01-26 09:02
try to add to the minisatip options -O

-O --satip-tcp Use RTSP over TCP insead of UDP for data transport

**Comment by stauraum** [comment] 2018-01-26 09:34
I've running minisatip8 with this option. With tvheadend rts-over-tcp is working, but VDR is my preferred DVR.

**Comment by 9000h** [comment] 2018-01-26 09:40
did you have an outdated libcurl (7.36.0 or greater is required)?

**Comment by stauraum** [comment] 2018-01-26 09:45
libcurl is 7.36.0-1fnu0~trusty

**Comment by 9000h** [comment] 2018-01-26 10:01
is there a Fritz!box in between with ports  in "Green Mode"?

**Comment by stauraum** [comment] 2018-01-26 10:32
No. There is a TP-Link with OpenWRT.

**Comment by 9000h** [comment] 2018-01-26 11:32
did you also try without -O, if your network is clean UDP should not  be an issue

**Comment by stauraum** [comment] 2018-01-26 11:40
yes. without -O there are sometimes disorders. I would use tcp-transport to know, if the issue appears.

**Comment by 9000h** [comment] 2018-01-26 11:56
I hope you have also adjust on the vdr/tvhedend side the kernel mem settings like

net.core.wmem_max=20491520
net.core.rmem_max=20491520
net.ipv4.tcp_mem = 65536 131072 262144
net.ipv4.udp_mem = 65536 131072 262144

**Comment by stauraum** [comment] 2018-01-26 12:00
I dont know if this works. My VDR and tvheadend are running inside docker containers. 

I will test this when my family-members are offline.

**Comment by 9000h** [comment] 2018-01-26 13:26
and by the way check nstat -a|grep Udp if you have unusual high or increasing UdpRcvbufErrors  or UdpInErrors

**Comment by rofafor** [comment] 2018-01-26 19:32
1) Verify, that the satip plugin is sending a proper transport header (RTP/AVP/TCP;unicast) in RTSP SETUP messages.
2) Verify, that the satip plugin detects your server with a proper name. It should contain a string "minisatip", otherwise the plugin won't allow you to use RTP-over-TCP
3) Verify, that Docker port forwarding settings are setup correctly and match with the "portrange" command-line parameter of the satip plugin.

**Comment by stauraum** [comment] 2018-01-27 07:51
@9000h i will check this soon

@rofafor 
1. How can ich check this?
2. The automatic detection works successful
3. VDR runs in Host-mode, no port forwardings needed.

**Comment by CvH** [comment] 2018-01-27 10:52
@stauraum random idea, install LibreELEC at an VM/RPi ... and activate the vdr addon there (with included vdr-plugin-satip) if it works there - then you can rule out that it is a problem of the box at least

**Comment by stauraum** [comment] 2018-01-31 12:16
@CvH i've installed LibreELEC in a VirtualBox. The Problem appears.

When i switch to rtsp-over-tcp there are some connection failures.

At the moment i'm running tvheadend fine and stable with 5 connected clients. The webinterface is very terrible an i'm missing the clear text configuration. But it's working at the moment.

**Comment by stauraum** [comment] 2018-01-31 13:11
@CvH i've installed LibreELEC in a VirtualBox. The Problem appears.

When i switch to rtsp-over-tcp there are some connection failures.

At the moment i'm running tvheadend fine and stable with 5 connected clients. The webinterface is very terrible an i'm missing the clear text configuration. But it's working at the moment.

**Comment by rofafor** [comment] 2018-01-31 19:18
@stauraum, you can use tcpdump/wireshark/tshark/your_favourite_capture_application to capture RTSP traffic on port 554 (or whatever you've configured on your minisatip).

**Comment by 9000h** [comment] 2018-02-04 00:05
if you set the satip plugin to unicast it works, rtsp-over-tcp did not work
```
Feb  3 23:25:12 Acer vdr: [12901] curl_easy_perform() [rtsp.c,350] failed: Timeout was reached (28)
Feb  3 23:25:12 Acer vdr: [12901] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.178.129/ [device 0]
Feb  3 23:25:12 Acer vdr: [12901] SATIP-ERROR: Connect failed [device 0]
Feb  3 23:25:14 Acer vdr: [12901] curl_easy_perform() [rtsp.c,225] failed: Timeout was reached (28)
Feb  3 23:25:14 Acer vdr: [12901] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.178.129/ [device 0]
Feb  3 23:25:14 Acer vdr: [12901] SATIP-ERROR: Connect failed [device 0]
```

**Comment by 9000h** [comment] 2018-02-05 21:54
RTP-over-TCP works for any SD channel here but not for HD channels, strange

**Comment by 9000h** [comment] 2018-02-06 13:25
I try to debug but could not find if the plugin or minisatip is the issue
http://paste.ubuntu.com/26529836/

**Comment by 9000h** [comment] 2018-02-06 13:35
found a minor typo also
```
--- socket.c.orig       2018-02-06 14:34:11.822574200 +0100
+++ socket.c    2018-02-06 14:34:42.902233383 +0100
@@ -128,7 +128,7 @@

 void cSatipSocket::Close(void)
 {
-  debug1("%s sockerPort=%d", __PRETTY_FUNCTION__, socketPortM);
+  debug1("%s socketPort=%d", __PRETTY_FUNCTION__, socketPortM);
   // Check if socket exists
   if (socketDescM >= 0) {
      Leave();
```

**Comment by 9000h** [comment] 2018-02-06 15:21
looks like the issue is in function SetupTransport tuner.c:705, there is duplicate code in

**Comment by 9000h** [comment] 2018-02-06 17:46
tcpdump port 554 and tcp -vvv
```
18:42:08.179021 IP (tos 0x0, ttl 64, id 23114, offset 0, flags [DF], proto TCP (6), length 2948)
    satip.fritz.box.rtsp > Acer.fritz.box.50162: Flags [.], cksum 0xf1b3 (incorrect -> 0x8e00), seq 11716218:11719114, ack 1718, win 107, options [nop,nop,TS val 2940015131 ecr 1116969722], length 2896: RTSP
18:42:08.193820 IP (tos 0x0, ttl 64, id 37859, offset 0, flags [DF], proto TCP (6), length 52)
    Acer.fritz.box.50162 > satip.fritz.box.rtsp: Flags [.], cksum 0xcd89 (correct), seq 1718, ack 11719114, win 1, options [nop,nop,TS val 1116969743 ecr 2940015130], length 0
18:42:08.193920 IP (tos 0x0, ttl 64, id 37860, offset 0, flags [DF], proto TCP (6), length 253)
    Acer.fritz.box.50162 > satip.fritz.box.rtsp: Flags [P.], cksum 0x8430 (correct), seq 1718:1919, ack 11719114, win 1, options [nop,nop,TS val 1116969743 ecr 2940015130], length 201: RTSP, length: 201
	PLAY rtsp://192.168.178.129/stream=1?src=1&freq=11493&pol=h&ro=0.35&msys=dvbs2&mtype=8psk&sr=22000&fec=23 RTSP/1.0
	CSeq: 11
	Session: 1633108117
	User-Agent: vdr-satip/2.3.1-GIT-e008ee0 (device 0)
	
18:42:08.194506 IP (tos 0x0, ttl 64, id 37861, offset 0, flags [DF], proto TCP (6), length 52)
    Acer.fritz.box.50162 > satip.fritz.box.rtsp: Flags [.], cksum 0xccb8 (correct), seq 1919, ack 11719114, win 8, options [nop,nop,TS val 1116969744 ecr 2940015130], length 0
18:42:08.195103 IP (tos 0x0, ttl 64, id 37862, offset 0, flags [DF], proto TCP (6), length 52)
    Acer.fritz.box.50162 > satip.fritz.box.rtsp: Flags [.], cksum 0xccb0 (correct), seq 1919, ack 11719114, win 16, options [nop,nop,TS val 1116969744 ecr 2940015130], length 0
18:42:08.197744 IP (tos 0x0, ttl 64, id 23116, offset 0, flags [DF], proto TCP (6), length 1500)
    satip.fritz.box.rtsp > Acer.fritz.box.50162: Flags [.], cksum 0xec93 (correct), seq 11719114:11720562, ack 1718, win 107, options [nop,nop,TS val 2940015151 ecr 1116969743], length 1448: RTSP
18:42:08.198044 IP (tos 0x0, ttl 64, id 23117, offset 0, flags [DF], proto TCP (6), length 2948)
    satip.fritz.box.rtsp > Acer.fritz.box.50162: Flags [.], cksum 0xf1b3 (incorrect -> 0x4777), seq 11720562:11723458, ack 1718, win 107, options [nop,nop,TS val 2940015151 ecr 1116969743], length 2896: RTSP
18:42:08.198076 IP (tos 0x0, ttl 64, id 37863, offset 0, flags [DF], proto TCP (6), length 52)
```
a tcpdump  port 554 and udp -vvv shows no traffic

**Comment by rofafor** [comment] 2018-02-06 18:22
Can you capture SETUP command (and the response) before the PLAY command? The UDP traffic isn't on the port 554, but on a random selected socket pair that's defined in the SETUP response.

**Comment by 9000h** [comment] 2018-02-06 19:30
tcpdump -n  host 192.168.178.129 -w /tmp/dump.pcap  (with the patch active)
[dump.pcap.gz](https://github.com/rofafor/vdr-plugin-satip/files/1700549/dump.pcap.gz)

**Comment by rofafor** [comment] 2018-02-06 21:00
The dump looks valid, but your SetupTransport hack doesn't as you're just opening ports 0 and 1 for UDP in it. However, I noticed two bugs in the code that are now fixed in master, but I doubt they will make any difference for this issue.

**Comment by 9000h** [comment] 2018-02-06 21:30
it makes a difference but there are still issues 
a vdr log with -t 0xff

[syslog.txt.gz](https://github.com/rofafor/vdr-plugin-satip/files/1700852/syslog.txt.gz)

**Comment by rofafor** [comment] 2018-02-06 21:57
Minisatip doesn't answer to PLAY command issued at Feb  6 22:18:50 in 1.5 seconds and RTSP session is re-created. This should be debugged with a network capture to see, whether the minisatip really got the message and did it responded back, but libcurl messed up the message or something. Make sure, you're using the latest libcurl version!

**Comment by 9000h** [comment] 2018-02-06 22:52
curl 7.47.0
the same test tcpdump
my impression is the satip plugin did close the socket somehow

[dump.pcap.gz](https://github.com/rofafor/vdr-plugin-satip/files/1701093/dump.pcap.gz)

**Comment by 9000h** [comment] 2018-02-07 12:10
it did not work right up to now, but it works better on low bandwidth SD channels
could it be that the video data / control data is getting in now handled wrong

**Comment by 9000h** [comment] 2018-02-07 17:38
rtsp.c  SATIP_CURL_EASY_SETOPT(handleM, CURLOPT_MAX_RECV_SPEED_LARGE, eMaxDownloadSpeedMBits * 131072L);
looks like this is also part of the issue, as I had SD channel that did work but HD channels did not, if it's commented out HD channels did work better but still with artifacts (all channels are fine with UDP)

**Comment by rofafor** [comment] 2018-02-07 18:54
So, you're saying that 20Mbit/s is not enough for your HD channels. What's the actual bitrate of those channels? Please, check your network stack buffer sizes and make sure, they are big enough.

The problem is that satip plugin doesn't get any PLAY responses from minisatip during the interleaved data and the requests timeout that leads to re-tuning loop. This could be a bug in satip plugin or libcurl, but I didn't notice such behaviour when I implemented the feature against the minisatip, but the server and client were on the same host. The RTP-over-TCP is just an experimental feature in the plugin and the performance is much worse than with UDP due to the current design. As the protocol isn't even included in the SAT>IP specifications, the implementation will exists as a dirty hack in the future too.

**Comment by 9000h** [comment] 2018-02-07 19:02
you have to take also in account the overhead of tcp, 20 bytes gets consumed more per packet.

**Comment by 9000h** [comment] 2018-02-07 20:14
I understand your position about the RTP-over-TCP, but it could be beneficial if you have some unreliable device like powerline adapters in between. I do not have any issue with UDP here.

The latest tcpdump I did upload did show all play requests get answered by minisatip if I did not overlooked something.

I will not insist any further.

**Comment by rofafor** [comment] 2018-02-07 20:53
Removing the download limit is ok for satip as it's for live streaming only and therefore the receiving buffer is harder to get over/underflow.
If you take a look at your latest packet capture and add a "rtsp.request || rtsp.response" filter, you'll see that there aren't any responses for RTSP PLAY commands after 5.5 seconds until the RTSP connection is teared down and re-created (OPTIONS) at 12.9 seconds. I might be using the libcurl interface in an invalid way, but the commands are shown in network traffic, so I doubt it.  For me it looks like minisatip isn't listening RTSP commands or drops these packets while sending the interleaved data back.

**Comment by rofafor** [comment] 2018-02-13 15:28
The speed limit has now been removed.

**Comment by catalinii** [comment] 2018-02-14 05:50
Feel free to upload also the minisatip logs ( -l http ) with the tcpdump capture.

Thanks

**Comment by 9000h** [comment] 2018-10-04 19:28
btw. minisatip rtp-over-tcp is working with tvheadend and also with VLC
the vdr-plugin-satip did run in some reconnect timeout an did re-tune every 2 Seconds

for tests you can set VLC to TCP in the advanced settings
https://www.wowza.com/docs/how-to-configure-vlc-media-player-for-rtsp-rtp-playback-rtsp-rtp-interleaved-and-tuning
![screenshot from 2018-10-04 21-20-26](https://user-images.githubusercontent.com/3009073/46497766-c768b380-c81b-11e8-8292-c354bd75b687.png)

**Comment by 9000h** [comment] 2018-10-11 22:07
I did some experiments and found a way to get rtsp-over-tcp going, but it did break Unicast
```
bool cSatipTuner::KeepAlive(bool forceP)
{
  debug16("%s (%d) tunerState=%s [device %d]", __PRETTY_FUNCTION__, forceP, TunerStateString(currentStateM), deviceIdM);
  cMutexLock MutexLock(&mutexM);
  if (keepAliveM.TimedOut()) {
     keepAliveM.Set(timeoutM);
     forceP = true;
     }
  if (forceP && !isempty(*streamAddrM)) {
     cString uri = GetBaseUrl(*streamAddrM, streamPortM);
     if (!rtspM.Options(*uri))
        return false;
     }
     cString uri = GetBaseUrl(*streamAddrM, streamPortM);
     rtspM.Options(*uri);

  return true;
}
```
how to get it right 
https://stackoverflow.com/questions/38733021/libcurl-rtsp-keep-alive-with-rtsp-server

**Comment by rofafor** [comment] 2018-10-13 14:38
I don't understand your solution - you'll have to send the OPTIONS command twice?

**Comment by 9000h** [comment] 2018-10-15 19:43
this works also for both
```
bool cSatipTuner::KeepAlive(bool forceP)
{
  debug16("%s (%d) tunerState=%s [device %d]", __PRETTY_FUNCTION__, forceP, TunerStateString(currentStateM), deviceIdM);
  cMutexLock MutexLock(&mutexM);
  if (keepAliveM.TimedOut()) {
     keepAliveM.Set(timeoutM);
     }

  if (!isempty(*streamAddrM)) {
     cString uri = GetBaseUrl(*streamAddrM, streamPortM);
     rtspM.Options(*uri);
     }

  return true;
}
```

**Comment by rofafor** [comment] 2018-10-16 13:51
So, it's the ```forceP``` flag that's not behaving correctly within TCP mode. Can you check, how does the Session header of SETUP command look like - the plugin might not parse that properly and therefore ```keepAliveM``` timer is not working as it should.

**Comment by 9000h** [comment] 2018-10-16 15:38
Hi,
should this not be already visible the dump above https://github.com/rofafor/vdr-plugin-satip/issues/47#issuecomment-363592795
CU
9000h

**Comment by 9000h** [comment] 2018-10-16 15:43
so this is it
```
OPTIONS rtsp://192.168.178.129/ RTSP/1.0
CSeq: 1
User-Agent: vdr-satip/2.3.1-GIT-8dc4844 (device 0)

RTSP/1.0 200 OK
Date: Tue, Feb 6 22:44:52 2018 GMT
Cseq: 1
Public: OPTIONS, DESCRIBE, SETUP, PLAY, TEARDOWN
Server: minisatip/0.7.15

SETUP rtsp://192.168.178.129/?src=1&freq=11493&pol=h&ro=0.35&msys=dvbs2&mtype=8psk&sr=22000&fec=23 RTSP/1.0
CSeq: 2
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
User-Agent: vdr-satip/2.3.1-GIT-8dc4844 (device 0)

RTSP/1.0 200 OK
Date: Tue, Feb 6 22:44:52 2018 GMT
Cseq: 2
Transport: RTP/AVP/TCP;interleaved=0-1
Session: 1804289383;timeout=30
com.ses.streamID: 1
Server: minisatip/0.7.15

DESCRIBE rtsp://192.168.178.129/stream=1 RTSP/1.0
CSeq: 3
Session: 1804289383
Accept: application/sdp
User-Agent: vdr-satip/2.3.1-GIT-8dc4844 (device 0)

RTSP/1.0 200 OK
Date: Tue, Feb 6 22:44:52 2018 GMT
Session: 1804289383
Cseq: 3
Content-type: application/sdp
Content-Base: rtsp://192.168.178.129/
Server: minisatip/0.7.15
Content-Length: 250

v=0
o=- 1804289383 1804289383 IN IP4 192.168.178.129
s=SatIPServer:1 4 4 2
t=0 0
m=video 0 RTP/AVP 33
c=IN IP4 0.0.0.0
a=control:stream=1
a=fmtp:33 ver=1.0;src=1;tuner=1,255,1,15,11493,h,8psk,,0.35,dvbs2,22000,23;pids=
b=AS:5000
a=inactive
PLAY rtsp://192.168.178.129/stream=1?addpids=5101,5102 RTSP/1.0
CSeq: 4
Session: 1804289383
User-Agent: vdr-satip/2.3.1-GIT-8dc4844 (device 0)

RTSP/1.0 200 OK
Date: Tue, Feb 6 22:44:52 2018 GMT
Session: 1804289383
Cseq: 4
RTP-Info: url=rtsp://192.168.178.129/stream=1;seq=6141;rtptime=2958453
Range: npt=0.000-
Server: minisatip/0.7.15

PLAY rtsp://192.168.178.129/stream=1?src=1&freq=11493&pol=h&ro=0.35&msys=dvbs2&mtype=8psk&sr=22000&fec=23 RTSP/1.0
CSeq: 5
Session: 1804289383
User-Agent: vdr-satip/2.3.1-GIT-8dc4844 (device 0)

RTSP/1.0 200 OK
Date: Tue, Feb 6 22:44:52 2018 GMT
Session: 1804289383
Cseq: 5
RTP-Info: url=rtsp://192.168.178.129/stream=1;seq=6172;rtptime=2958453
Range: npt=0.000-
Server: minisatip/0.7.15

PLAY rtsp://192.168.178.129/stream=1?pids=0,17,18,20,5101,5102,5103,5105,5106 RTSP/1.0
CSeq: 6
Session: 1804289383
User-Agent: vdr-satip/2.3.1-GIT-8dc4844 (device 0)

RTSP/1.0 200 OK
Date: Tue, Feb 6 22:44:52 2018 GMT
Session: 1804289383
Cseq: 6
RTP-Info: url=rtsp://192.168.178.129/stream=1;seq=6187;rtptime=2958453
Range: npt=0.000-
Server: minisatip/0.7.15
```

**Comment by rofafor** [comment] 2018-10-16 18:09
So it's 30 seconds then. Unfortunately your captures are too short for checking what's happening during the keep-alive OPTIONS command. It would be great if you could capture that with the faulty (current master) and working (your patch) setup.

**Comment by 9000h** [comment] 2018-10-16 19:57
plain vanilla plugin
tcpdump -ni any port 554 -w dump.pcap -s 0

https://drive.google.com/file/d/1DGSoGadvGyfm9LbDMHnkDZUQaU3JTTi4/view

**Comment by 9000h** [comment] 2018-10-16 20:03
now with the patch
https://drive.google.com/file/d/1611jhY5N3qyOs2f_6eeqreqszzBDznhr/view

**Comment by rofafor** [comment] 2018-10-16 20:22
Good. So, the both are actually broken. Can you enable some debug output in vanilla plugin:
1) cSatipTuner::SetSessionTimeout()
- values of ```timeoutP``` parameter and ```timeoutM``` member variables
2) cSatipTuner::KeepAlive()
- when the function is called - I need just timestamps
3) cSatipRtsp::Options()
- when the function is called
- value of return code aka. ```rc```
- value of ```result```

**Comment by 9000h** [comment] 2018-10-16 21:15
with -t01 and additional "tcpdebug" , not sure if this is sufficent
https://pastebin.com/MxQPU02S

**Comment by rofafor** [comment] 2018-10-17 05:48
Oh, I see. Your problem is the re-connection timeout and not the keep-alive. Somehow, the video data streaming doesn't start with a PLAY command, but requires one-time or constant RTSP communication, that you've been dealing with OPTIONS commands.

**Comment by rofafor** [comment] 2018-10-17 12:01
I'll try to setup a proper minisatip environment, but it won't happen this week.

**Comment by 9000h** [comment] 2018-10-17 13:07
there's no rush
thank's

**Comment by 9000h** [comment] 2018-10-21 14:45
should this be the final fix 8130a4b4e5dbe829ad6cf8782f4793635 , if so then there is still an issue with the keep-alive as I have connection timeout issues with the latest git

the timeout is now every 5 seconds before it was every 2 seconds
```
Oct 21 15:53:10 acer533 vdr: [2077] starting plugin: satip
Oct 21 15:53:10 acer533 vdr: [2077] SATIP: Using CURL 7.58.0 rtsp
Oct 21 15:53:10 acer533 vdr: [2081] SATIP: Adding server '192.168.178.113|DVBS2-4,DVBC-2,DVBT2-2,DVBC2-2|minisatip' Bind: default Filters: none CI: yes Quirks: RtpOverTcp,CiXpmt
Oct 21 15:53:10 acer533 vdr: [2081] SATIP: Adding server '192.168.178.1|DVBC-4|FRITZ!Box 6490 Cable' Bind: default Filters: none CI: no Quirks: PlayPids,ForceLock
Oct 21 15:53:17 acer533 vdr: [2082] SATIP-ERROR: Connection timeout - retuning [device 0]
Oct 21 15:53:17 acer533 vdr: [2082] SATIP: Detected 1 RTP packet error [device 0]
Oct 21 15:53:22 acer533 vdr: [2082] SATIP-ERROR: Connection timeout - retuning [device 0]
Oct 21 15:53:28 acer533 vdr: [2082] SATIP-ERROR: Connection timeout - retuning [device 0]
Oct 21 15:53:33 acer533 vdr: [2082] SATIP-ERROR: Connection timeout - retuning [device 0]
```

**Comment by rofafor** [comment] 2018-10-21 16:07
That commit fixed only the existing RTCP issue.

**Comment by 9000h** [comment] 2018-10-21 17:41
ok makes sense

**Comment by rofafor** [comment] 2018-10-21 17:45
I've added an ugly fix for this one. It would be great, if someone could point out how the CURL_RTSPREQ_RECEIVE should be used.

**Comment by 9000h** [comment] 2018-10-21 17:57
98ecd22a2717a03d16433958e81be079c4fac7d8 did work now
thank's for fixing it!
there is a reference in lib571.c from curl tests

**Comment by 9000h** [comment] 2018-10-21 18:11
the only issue I can see now is in a mixed setup where one server supports rtsp-over-tcp and the other not
like here:
```
Oct 21 20:01:40 acer533 vdr: [5775] SATIP: Adding server '192.168.178.113|DVBS2-4,DVBC-2,DVBT2-2,DVBC2-2|minisatip' Bind: default Filters: none CI: yes Quirks: RtpOverTcp,CiXpmt
Oct 21 20:01:40 acer533 vdr: [5775] SATIP: Adding server '192.168.178.1|DVBC-4|FRITZ!Box 6490 Cable' Bind: default Filters: none CI: no Quirks: PlayPids,ForceLock
```
btw the Quirks for "FRITZ!Box 6490 Cable" and "FRITZ!Box 6590 Cable" are obsolete if they have "Fritz OS 7"

**Comment by 9000h** [comment] 2018-10-21 19:36
in case of a mixed setup and rtsp-over-tcp in the plugin menu is set, the minisatip server is working fine now but the Fritzbox will not work as there is no rtsp-over-tcp support implemented in the box. 
Unicast is working fine for both devices.

**Comment by 9000h** [comment] 2018-10-21 19:51
maybe a check if the interleave works at the server after SETUP helps to do a fallback to unicast
not sure what will be the best option to handle this
```
SETUP rtsp://192.168.178.129/?src=1&freq=11493&pol=h&ro=0.35&msys=dvbs2&mtype=8psk&sr=22000&fec=23 RTSP/1.0
CSeq: 2
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
User-Agent: vdr-satip/2.3.1-GIT-8dc4844 (device 0)

RTSP/1.0 200 OK
Date: Tue, Feb 6 22:44:52 2018 GMT
Cseq: 2
Transport: RTP/AVP/TCP;interleaved=0-1
Session: 1804289383;timeout=30
com.ses.streamID: 1
Server: minisatip/0.7.15
```

**Comment by rofafor** [comment] 2018-10-23 19:49
A proper fix is still missing, so let's keep this open until it's done.

**Comment by Wanninger** [comment] 2021-01-20 11:04
I've recently been trying to get rtsp-over-tcp working with this plugin on the minisatip server. While searching for info on this, I came across this ticket.

What is the current status here?

With my setup it already fails at the setup of the client to the server. Already here no TCP is requested under transport.
I have tried it with 2.3.1 and also with 2.4.1 on several VDRs. Unfortunately everywhere the same.
As a cross-check, to be able to exclude the minisatip server as an error, I tried it with VLC. There RTSP over TCP works perfectly together with minisatip.

Thanks

**Comment by 9000h** [comment] 2021-01-20 16:53
VDR and minisatip with rtp-over-tcp did work 
```
Jan 20 17:46:24 localhost minisatip[10565]: [20/01 17:46:24.955 main]: MSG client >> process :
Jan 20 17:46:24 localhost minisatip[10565]: SETUP rtsp://192.168.178.129/?freq=330&msys=dvbc&mtype=256qam&sr=6900 RTSP/1.0
Jan 20 17:46:24 localhost minisatip[10565]: CSeq: 2
Jan 20 17:46:24 localhost minisatip[10565]: Transport: RTP/AVP/TCP;unicast;interleaved=0-1
Jan 20 17:46:24 localhost minisatip[10565]: User-Agent: vdr-satip/2.4.1-GIT-df81905 (device 0)
Jan 20 17:46:24 localhost minisatip[10565]: #015
Jan 20 17:46:24 localhost minisatip[10565]: [20/01 17:46:24.955 main]: detect_dvb_parameters (S)-> freq=330&msys=dvbc&mtype=256qam&sr=6900
Jan 20 17:46:24 localhost minisatip[10565]: [20/01 17:46:24.955 main]: detect_dvb_parameters (E) -> src=0, fe=0, freq=330000, fec=9, sr=6900000, pol=0, ro=3, msys=1, mtype=5, plts=2, bw=8000000, inv=2, pids=NULL - apids=NULL - dpids=NULL x_pmt=NULL
Jan 20 17:46:24 localhost minisatip[10565]: [20/01 17:46:24.955 main]: Setup stream sid -1 parameters, sock_id 7, handle 7
```

**Comment by Wanninger** [comment] 2021-01-20 18:58
This is interesting. I have even compiled the same tags that worked for you, but they didn't work for me. There must be differences somewhere. It can't be the minisatip server, because it streams TCP with VLC flawlessly.

Which Linux / VDR /... Version do you use?
With which start parameters do you start VDR or the satip plugin?
Is the VDR vanilla, or patched?

I'll attach a trace excerpt later that shows it cleanly

**Comment by 9000h** [comment] 2021-01-20 19:09
vdr 2.4.1 with some patches but I do not think there is a issue, but it could be the curl version(mine is curl 7.68.0)

**Comment by 9000h** [comment] 2021-01-20 19:12
but if there is no good reason you should use unicast, the rtsp-over-tcp is not well tested and @rofafor likes a proper implementation as you can read some posts obove

**Comment by Wanninger** [comment] 2021-01-20 19:13
Wich Linux distro do you use?

**Comment by 9000h** [comment] 2021-01-20 19:14
it's Ubuntu 20.04.2 focal

**Comment by Wanninger** [comment] 2021-01-20 19:16
With curl 7.68 out of your Ubuntu?

**Comment by Wanninger** [comment] 2021-01-20 19:20
With RTSP over TCP, WAN streams work much more stable. This is actually the only reason for TCP in my environment.

**Comment by 9000h** [comment] 2021-01-20 19:24
yes but 7.58 should do also
apt-cache policy curl

curl:
  Installed: 7.68.0-1ubuntu2.4
  Candidate: 7.68.0-1ubuntu2.4
  Version table:
 *** 7.68.0-1ubuntu2.4 500
        500 http://de.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
        100 /var/lib/dpkg/status
     7.68.0-1ubuntu2 500
        500 http://de.archive.ubuntu.com/ubuntu focal/main amd64 Packages

**Comment by 9000h** [comment] 2021-01-20 19:28
please try first rtsp-over-tcp in you local LAN, and if it's not working show us the logs from vdr and minisatip, maybe a packet capture also helps to debug

**Comment by Wanninger** [comment] 2021-01-20 19:36
Thanks for the info. I was going to install a new computer anyway. Then I will connect that right away and test RTSC/TCP again...

Thanks for the info. I was going to install a new computer anyway. Then I can test the RTSP/TCP with the newer versions.
Currently my latest curl version is the 7.52 from the MLD-5.4, but it doesn't work with that yet.

All tests so far have been exclusively on the LAN.

**Comment by 9000h** [comment] 2021-01-21 08:04
hmm, it may looks like it's as simple as replacing Server2 with minisatip

https://github.com/rofafor/vdr-plugin-satip/blob/a7625c028c460b8350a023db495e2b6b0bc93607/server.c#L177
or you need to enable the needed quirks manually

**Comment by Wanninger** [comment] 2021-01-21 09:18
Wow, so simple, ...Server1...3 is assigned by the MLD via the WebIF. Just took this value for my manual tests and never gave a thought that this value is crosschecked by the satip plugin....

Anyway, it runs with it.

Many thanks for your support and clarification

**Comment by rofafor** [comment] 2021-01-22 21:15
This issue is still open due to this issue: https://github.com/rofafor/vdr-plugin-satip/blob/master/rtsp.c#L221
I couldn't figure out, why it didn't work as specified.

**Comment by Wanninger** [comment] 2021-01-23 09:27
> This issue is still open due to this issue: https://github.com/rofafor/vdr-plugin-satip/blob/master/rtsp.c#L221
> I couldn't figure out, why it didn't work as specified.

Unfortunately, I am not a programmer, so I have only a rudimentary idea of what this line is about.

But I can, if there is a need, offer my help for tests. I have enough equipment at my disposal.

**Comment by hpannenb** [comment] 2021-03-10 16:13
> This issue is still open due to this issue: https://github.com/rofafor/vdr-plugin-satip/blob/master/rtsp.c#L221
> I couldn't figure out, why it didn't work as specified.

@rofafor Do You now the (short) mail thread from the curl mailinglings under [How to get a frame of image data from rtsp stream](https://curl.se/mail/lib-2014-02/0067.html)? Maybe the reply gives some help into the proper direction?

**Comment by rofafor** [comment] 2021-03-13 18:53
That linked issue looks pretty similar. One can't get the frames via RECEIVE command as it should according to the documentation and I've circumvent it by using OPTIONS command instead. However, I haven't tested the latest libcurl libraries, so might work nowadays.

**Comment by hpannenb** [comment] 2021-03-16 18:26
@rofafor Mhhh...I was searching for code examples but without any positive hits ... maybe this gives a hint to the proper direction [multi interface and RTSP interleved](https://www.mail-archive.com/curl-library@cool.haxx.se/msg25168.html) referencing to [RTSP Interleaved Multi Interface](https://curl.se/mail/lib-2016-03/0029.html)

**Comment by rofafor** [comment] 2021-05-30 12:26
Closing this due to inactivity. There's a `FIXME` comment in the code reminding about this.

**Closed by rofafor** 2021-05-30 12:26 UTC
