### ISSUE TITLE
FRITZ!Box quirks

### ISSUE THREAD

**Issue by 9000h** [rofafor/vdr-plugin-satip#38] opened 2017-07-17 18:07 UTC
Hi,

can you please add/change the FRITZ!Box quirks 

as reference:
http://www.vdr-portal.de/board16-video-disk-recorder/board8-vdr-grundlagen/p1294442-iptv-fritzbox-erledigt/#post1294442

the Fritz!Box limits the also 1 source IP to one tuner
it would be also great if an additional quirk for this limit goes in like in TVH
https://tvheadend.org/boards/4/topics/18013?r=22619#message-22619

here a the 2 xml sample files

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<root xmlns="urn:schemas-upnp-org:device-1-0" configId="0">


<specVersion>

<major>1</major>
<minor>0</minor>
</specVersion>


<device>

<deviceType>urn:ses-com:device:SatIPServer:1</deviceType>
<friendlyName>FRITZ!Box 6490 Cable</friendlyName>
<manufacturer>AVM Berlin</manufacturer>
<manufacturerURL>http://www.avm.de</manufacturerURL>
<modelDescription>FRITZ!Box 6490 Cable</modelDescription>
<modelName>FRITZ!Box 6490 Cable</modelName>
<modelNumber>avm</modelNumber>
<modelURL>http://www.avm.de</modelURL>
<serialNumber/>
<UDN>uuid:663d5d6c-f9f7-4bb4-84d4-5C3979431C37</UDN>
<iconList></iconList>


<serviceList>



<service>

<serviceType>urn:ses-com:service:satip:1</serviceType>
<serviceId>urn:ses-com:serviceId:satip</serviceId>
<controlURL>/upnp/control/satip</controlURL>
<eventSubURL>/upnp/control/satip</eventSubURL>
<SCPDURL>/satipSCPD.xml</SCPDURL>
</service>
</serviceList>
<presentationURL>http://fritz.box</presentationURL>
<satip:X_SATIPCAP xmlns:satip="urn:ses-com:satip">DVBC-2</satip:X_SATIPCAP>
</device>
</root> 
```
and the Fritz Repeater

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<root xmlns="urn:schemas-upnp-org:device-1-0" configId="0">



<specVersion>

<major>1</major>
<minor>0</minor>
</specVersion>


<device>

<deviceType>urn:ses-com:device:SatIPServer:1</deviceType>
<friendlyName>FRITZ!WLAN Repeater DVB-C</friendlyName>
<manufacturer>AVM Berlin</manufacturer>
<manufacturerURL>avm.de</manufacturerURL>
<modelDescription>FRITZ!WLAN Repeater DVB-C</modelDescription>
<modelName>FRITZ!WLAN Repeater DVB-C</modelName>
<modelNumber>avm</modelNumber>
<modelURL>avm.de</modelURL>
<serialNumber/>
<UDN>uuid:663d5d6c-f9f8-4bb4-84d4-3431C46D68B8</UDN>
<iconList></iconList>


<serviceList>



<service>

<serviceType>urn:ses-com:service:satip:1</serviceType>
<serviceId>urn:ses-com:serviceId:satip</serviceId>
<controlURL>/upnp/control/satip</controlURL>
<eventSubURL>/upnp/control/satip</eventSubURL>
<SCPDURL>/satipSCPD.xml</SCPDURL>
</service>
</serviceList>
<presentationURL>192.168.178.74</presentationURL>
<satip:X_SATIPCAP xmlns:satip="urn:ses-com:satip">DVBC-2</satip:X_SATIPCAP>
</device>
</root>

```

**Comment by CvH** [comment] 2017-07-17 18:52
https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/addons/service/tvheadend42/source/bin/tvheadend42.start#L92-L112 may help, that is necessary to support it at Tvheadend.

Per IP only one tuner could be accessed, the announcement of the `satipdesc.xml` is at the Repeater IP for the AVM Repeater, for the AVM 6490/6590 at xxx.xxx.xxx.254.

Besides that "awesome" implementation they are reported as perfectly working.

**Comment by rofafor** [comment] 2017-07-18 12:59
Added the quirks, but setting different source addresses for each frontend on the same device is a bit trickier.

**Comment by rofafor** [comment] 2017-07-19 17:25
@9000h, can you test the branch "bindif"? https://github.com/rofafor/vdr-plugin-satip/tree/bindif

1) Create virtual interfaces:
```
ifconfig eth0:1 192.168.0.101
ifconfig eth0:2 192.168.0.102
```
2) Start the plugin with correct parameters:
```
 -P 'satip -d 2 -s \"192.168.0.101@192.168.0.254|DVBC-1|fritzdvbc1;192.168.0.102@192.168.0.254|DVBC-1|fritzdvbc2\"'
```

**Comment by 9000h** [comment] 2017-07-19 17:59
will do and report

**Comment by Saman-VDR** [comment] 2017-07-21 11:41
Hi, I have a 'FRITZ!Box 6490 Cable' and a fresh yaVDR 0.6.1 with vdr-2.3.7 and satip (2.3.1-GIT-3f5e470) running.
Autodetection isn't working for me but the 'bindif' does it :)
I can record and watch from different transponders at same time.
But recording 'Das Erste HD' and watching 'ZDF HD' is to much for the FB. Live and Recording then have artifacts. Recording 'Das Erste HD' and zapping some SD channels is working well.

cat /etc/vdr/conf.avail/satip.conf
`-d 2 -s 192.168.178.201@192.168.178.254:554|DVBC-1|'FRITZ!Box 6490 Cable 1';192.168.178.202@192.168.178.254:554|DVBC-1|'FRITZ!Box 6490 Cable 2'`

cat /etc/network/interfaces
`# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet static
  address 192.168.178.200/24
  gateway 192.168.178.1
  dns-nameservers 192.168.178.1

# The virtual network interfaces
auto eth0:1
iface eth0:1 inet static
  address 192.168.178.201
  netmask 255.255.255.0

auto eth0:2
iface eth0:2 inet static
  address 192.168.178.202
  netmask 255.255.255.0`

**Comment by 9000h** [comment] 2017-07-21 12:10
I did not had the time yet to check it out probably on the weekend but
make also sure that you have the used gigabit ports on the Fritz!Box not in "green mode" this is an known issue.

on the Linux/VDR end you should also set some kernel parameters to improve streaming in general with sysctl on startup 

net.core.wmem_max=20491520
net.core.rmem_max=20491520
net.ipv4.tcp_mem = 65536 131072 262144
net.ipv4.udp_mem = 65536 131072 262144

**Comment by rofafor** [comment] 2017-07-21 13:02
@Saman-VDR, can you clarify your auto-detection issues? By default the plugin should detect your FRITZ!Box 6490 Cable device with two frontends (although you can use only one at the time).

**Comment by Saman-VDR** [comment] 2017-07-21 13:32
@9000h 
The ports are not in "green mode" and I will give your settings a try but I think the problem is inside AVM's firmware.

@rofafor 
The plugin doesn't detect the fritzbox. I tried this with different setup's. RPi with raspbian and vdr-2.2.0, Zotac ION with yaVDR and vdr-2.3.7
If I use minisatip with dvb-s2 on my vdrserver, the plugin detects the minisat-server.
So I think my network is ok, my setup is:
vdrserver <-> fb <-> switch -> clients
But later I will try again with the ION connected directly to the fritzbox to be sure.

**Comment by Saman-VDR** [comment] 2017-07-21 14:15
Tried both, connecting the client directly to the fb and changing kernel parameter.
Auto-detection is still not working and recording from 'Das Erste HD' and watching 'ZDF HD' is blocky.

**Comment by unf** [comment] 2017-07-21 14:27
@Saman-VDR 

Try to take your FB out of business as essential part of your network. Means don't use FB as switch for your network infrastructure. All those integrated switches are rather cheap switches. Don't get me wrong, I even run 2 FBs in my network, but only as "network clients" doing their specific jobs, e.g. router, Wifi AP, VoIP client ...

**Comment by Saman-VDR** [comment] 2017-07-21 15:24
@unf 
Yes you are right, but for the test, the vdrserver and all other clients were offline.
For my understanding, then it is the best to connect the client directly to the Sat>IP server.
If I use minisatip at my vdrserver, two and more HD channels simultaneously are not a problem.

**Comment by rofafor** [comment] 2017-07-21 20:02
@Saman-VDR, I just added a detectsatip.py script into the repo. Can you, please, run it and check the output?

**Comment by 9000h** [comment] 2017-07-21 20:37
I got here
[{'frontends': {'DVBC': 2}, 'name': 'FRITZ!Box 6490 Cable'},
 {'frontends': {'DVBC2': 2, 'DVBS2': 4, 'DVBT2': 2}, 'name': 'minisatip'}]

btw the FRITZ!Box 6490 Cable did report 2 tuners but in real it has 4

**Comment by rofafor** [comment] 2017-07-21 23:38
@9000h, thanks! I force-pushed the SO_REUSEPORT fix. According your results the auto-detection should work fine or are you having other issues than the wrong number of frontend (, but the device is announcing containing only two tuners)?

**Comment by 9000h** [comment] 2017-07-22 05:20
yes very strange implementation from AVM but it announces 2 tuners but in real there are 4
![screen shot 2017-07-22 at 07 17 27](https://user-images.githubusercontent.com/3009073/28488609-243db9de-6eae-11e7-8484-a2f8649821a5.png)

**Comment by Saman-VDR** [comment] 2017-07-22 07:50
@rofafor 

Firtzbox only:
./detectsatip.py
[]

For testing then I started the minisatip-server:
./detectsatip.py 
[{'frontends': {'DVBS2': 2}, 'name': 'minisatip'}]

**Comment by Saman-VDR** [comment] 2017-07-22 08:27
But if I unplug my SAMSUNG-TV from the lan, and wait 3 minutes I got
[{'frontends': {'DVBC': 2}, 'name': 'FRITZ!Box 6490 Cable'}]

????

**Comment by 9000h** [comment] 2017-07-22 09:18
if have only Panasonic TV's here and no issues with ssdp

**Comment by rofafor** [comment] 2017-07-22 10:43
@Saman-VDR, you're having something odd in your network configuration that's not directly related to this plugin.

Modified changes has been merged into the master branch and therefore I'm closing this issue.

**Closed by rofafor** 2017-07-22 10:43 UTC

**Comment by Saman-VDR** [comment] 2017-07-22 12:00
Just for the record, the odd device is a Samsung TV UE40D5700.

**Comment by 9000h** [comment] 2017-07-23 10:42
at least 2 HD streams work here without issues with a 6490

**Comment by Saman-VDR** [comment] 2017-07-23 11:18
@9000h 
for me, specially the combination of  'Das Erste HD' and 'ZDF HD' is not usable. Others are ok.
For my tests, the VDR was connected exclusive to the FB, no other devices.
Which firmware version did you use?

**Comment by 9000h** [comment] 2017-07-23 14:19
FB 06.83 and I did test also with  'Das Erste HD' and 'ZDF HD'

**Comment by 9000h** [comment] 2018-09-30 22:50
Fritz OS 7 with real SAT>IP support and no limit for one stream per ip, not sure if other quirks now also obsolete

the only major difference to detect the new OS 7 is DVBC-4 (before DVBC-2)
 
http://192.168.178.1:49000/satipdesc.xml
```
<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" configId="0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:ses-com:device:SatIPServer:1</deviceType>
<friendlyName>FRITZ!Box 6490 Cable</friendlyName>
<manufacturer>AVM Berlin</manufacturer>
<manufacturerURL>http://www.avm.de</manufacturerURL>
<modelDescription>FRITZ!Box 6490 Cable</modelDescription>
<modelName>FRITZ!Box 6490 Cable</modelName>
<modelNumber>avm</modelNumber>
<modelURL>http://www.avm.de</modelURL>
<serialNumber></serialNumber>
<UDN>uuid:663d5d6c-f9f8-4bb4-84d4-C80E14ABXXXX</UDN>
<iconList>
</iconList>
<serviceList>
<service>
<serviceType>urn:ses-com:service:satip:1</serviceType>
<serviceId>urn:ses-com:serviceId:satip</serviceId>
<controlURL>/upnp/control/satip</controlURL>
<eventSubURL>/upnp/control/satip</eventSubURL>
<SCPDURL>/satipSCPD.xml</SCPDURL>
</service>
</serviceList>
<presentationURL>http://192.168.178.1</presentationURL>
<satip:X_SATIPCAP xmlns:satip="urn:ses-com:satip">DVBC-4</satip:X_SATIPCAP>
</device>
</root>
```

**Comment by CvH** [comment] 2018-10-02 07:46
> Fritz OS 7 with real SAT>IP support

at every former DVB-C enabled FritzBox or just some models?
