### ISSUE TITLE
Feature request: add option for RTP unicast over TCP

### ISSUE THREAD

**Issue by HellGL** [rofafor/vdr-plugin-satip#23] opened 2016-06-20 07:38 UTC
I have some problems in my network accessing my GSS.Box SAT>IP server. I know, I should by an OctopusNet but anyway I found out, that I get only distortions and artefacts if I access it via RTSP and if I use http:// (VLC or mplayer) the picture is perfect. Another trial with VLC and rtsp:// showed a perfect picture after I activated "RTP over RTSP (TCP)" in the preferences. A quick hack in rtsp.c adding "/TCP" to line 193 improved the picture quality a lot:
`transport = cString::sprintf("RTP/AVP/TCP;unicast;client_port=%d-%d", rtpPortP, rtcpPortP);`
So do you think it is possible to activate the TCP option via a command line switch? I think it could be useful also for other users.

Best regards,
Helge

**Comment by CvH** [comment] 2016-06-20 07:54
@HellGL fyi the OctopusNet has the same problem but sadly no RTP/TCP support (not that I know)

**Comment by rofafor** [comment] 2016-06-20 14:28
The specs don't support TCP and I hesitate adding such non-compliant features.

**Comment by pbriesch** [comment] 2016-06-20 15:12
This additional feature will improve the usefulness of the vdr-plugin-satip and will help many people to get rid of artifacts.
Do the specs specifically do not allow to do this?
If the implementation does not break anything that the specs require the plugin will still be compliant. I will just have additional features.

**Comment by rofafor** [comment] 2016-06-20 16:01
Can you, please, verify the functionality of this PR: https://github.com/rofafor/vdr-plugin-satip/pull/24

**Comment by CvH** [comment] 2016-06-20 16:02
RTP/UDP is "broken" by design - that is why "every" sat>ip server supports also RTP/TCP (at least minisatip, Tvh and DVBViewer). For example at an Raspberry Pi you have nearly no chance to use VDR without errors due dropped udp packages (because the RPi has an shitty network stack). Also at normal hardware you can get these problems - mostly if you use more then one switch in the network.

**Comment by rofafor** [comment] 2016-06-20 16:16
Well, I don't have any issues on my network with multiple switches or even with Android tablet over WiFi using RTP-over-UDP.

**Comment by rofafor** [comment] 2016-06-20 16:32
@CvH: can you provide the friendly names (root/device/friendlyName in their discovery xml) of Tvheadend and DVBViewer, so I can add RTP-over-TCP quirks for them too?

**Comment by CvH** [comment] 2016-06-20 19:28
@rofafor 
DVBViewer
```
<friendlyName>DVBViewer Media Server (HOSTNAME-of-SERVER)</friendlyName>
<manufacturer>cmuv</manufacturer>
<manufacturerURL>http://www.dvbviewer.com/</manufacturerURL>
<modelDescription>DVBViewer Mediaserver</modelDescription>
<modelName>DVBViewer Mediaserver</modelName>
```

%s%s is the Tvheadend server name - this could be freely changed in the settings
```
<friendlyName>%s%s</friendlyName>
<manufacturer>TVHeadend Team</manufacturer>
<manufacturerURL>http://tvheadend.org</manufacturerURL>
<modelDescription>TVHeadend %s</modelDescription>
<modelName>TVHeadend SAT>IP</modelName>
```

**Comment by rofafor** [comment] 2016-06-21 20:08
Feature merged into master - although no support for TVHeadend.

**Closed by rofafor** 2016-06-21 20:08 UTC

**Comment by CvH** [comment] 2016-06-21 20:47
@rofafor any particular reason to not support Tvh ?

**Comment by rofafor** [comment] 2016-06-22 06:18
The plugin is using friendlyName for detection and that field seems to be totally user configurable in Tvh. Ofcourse, you can provide me a PR with a more complete mechanism, but for today the friendlyName has been the only single field differentiating all the devices.

**Comment by CvH** [comment] 2016-06-22 08:59
@rofafor tx for explenation
